### ISSUE TITLE
Broken with Pandas 1.2

### ISSUE THREAD

**Issue by jcklie** [CODAIT/Identifying-Incorrect-Labels-In-CoNLL-2003#40]
When I install the requirements via pip and then run python  scripts/download_and_correct_corpus.py, I get

```AttributeError: module 'pandas.core.ops' has no attribute '_get_op_name'```

I run on WIndows with python 3.9.2. I saw a similar issue in https://github.com/hgrecco/pint-pandas/issues/51 .

**Comment by WatsonZhou12** [comment]
Hi, at first I encountered the same problem as you until I realized the pandas was installed from "
text-extensions-for-pandas". 
[https://github.com/CODAIT/text-extensions-for-pandas/blob/master/requirements.txt](url)
So I changed the latest version back to 1.0.3 and the problem fixed.

**Comment by frreiss** [comment]
Thanks for catching this! I've pushed some updates (in b1eccd827cf7b7b3bfd8b09f2e5e57a252527c6f) that upgrade the Text Extensions for Pandas dependency to a version that works with Pandas 1.2. The `download_and_correct_corpus.py` script is working again now.

**Comment by frreiss** [comment]
Created a new point release (https://github.com/CODAIT/Identifying-Incorrect-Labels-In-CoNLL-2003/releases/tag/0.2.1) that incorporates the fix. Will close this issue now.
